### ISSUE TITLE
Not compatible with 3.3.2

### ISSUE THREAD

**Issue by dsconstable** [USGS-R/USGSHydroTools#25]
I tried installing this package, but it appears to not be working with version 3.3.2. Do you have advice on how to make this install? Thank you.

> install.packages("USGSHydroTools")
Installing package into ‘/Users/ishi/Library/R/3.3/library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘USGSHydroTools’ is not available (for R version 3.3.2)

**Comment by ldecicco-USGS** [comment]
I'm wondering if you are installing from the "GRAN" repository. If you check out the readme, there are pretty specific instructions, but in a nutshell, you could install like this:

```
install.packages("USGSHydroTools", repos=c("https://owi.usgs.gov/R","https://cloud.r-project.org"))

```

(I just tried, and it did install on my R 3.3.2

**Comment by dsconstable** [comment]
@ldecicco-USGS, thank you, that fixed it. I thought I had followed the read me, but must have used switched the repository. It is now working on R 3.3.2
